import type { AssignmentType, CourseLevel, Department, Scenario } from '@/types';

// ── Catalogue metadata (no card content loaded until needed) ──────────────────

export type ScenarioMeta = {
  id: string;
  title: string;
  titleEs: string;
  description: string;
  department: Department;
  difficulty: 1 | 2 | 3;
  isFree: boolean;
  personaPreview: string;
  durationMinutes: number;
  courseLevels: CourseLevel[];
  /**
   * Which real oral-exam assignment type this scenario is a practice
   * equivalent of (types/mock.ts's AssignmentType) — the taxonomy the daily
   * guided session's Step 2 rotates through, so "today's role-play" is
   * always literally something that can appear on the exam. Undefined for
   * scenarios that don't map cleanly onto one (e.g. lost-luggage) — those
   * stay browsable in Practice but are excluded from the daily rotation.
   */
  assignmentType?: AssignmentType;
};

export const SCENARIO_CATALOG: ScenarioMeta[] = [
  {
    id: 'noisy-room-complaint',
    title: 'Noisy Room Complaint',
    titleEs: 'Queja por ruido',
    description: 'A tired guest has been kept awake by noise and demands a solution.',
    department: 'front_office',
    difficulty: 1,
    isFree: true,
    personaPreview: 'Mr. Anderson · British · frustrated',
    durationMinutes: 5,
    courseLevels: ['basic', 'intermediate'],
    assignmentType: 'complaint',
  },
  {
    id: 'restaurant-allergy-order',
    title: 'Restaurant Allergy Order',
    titleEs: 'Pedido con alergia',
    description: 'A guest with a nut allergy needs safe menu guidance before ordering.',
    department: 'fnb',
    difficulty: 2,
    isFree: true,
    personaPreview: 'Madame Dupont · French · composed',
    durationMinutes: 6,
    courseLevels: ['basic', 'intermediate'],
    assignmentType: 'restaurant',
  },
  {
    id: 'overbooking',
    title: 'Overbooking Crisis',
    titleEs: 'Crisis de overbooking',
    description: 'The hotel is overbooked and the guest\'s reserved room is unavailable.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Don Ramírez · Mexican · demanding',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'checkin',
  },
  {
    id: 'lost-luggage',
    title: 'Lost Luggage',
    titleEs: 'Equipaje perdido',
    description: 'A distressed guest arrives after a long flight with no suitcases.',
    department: 'concierge',
    difficulty: 3,
    isFree: false,
    personaPreview: 'Ms. Kim · Korean · distressed',
    durationMinutes: 8,
    courseLevels: ['intermediate'],
  },

  // ── Check-in ──────────────────────────────────────────────────────────────
  {
    id: 'checkin-walk-in-no-reservation',
    title: 'Walk-In, No Reservation',
    titleEs: 'Llegada sin reserva',
    description: 'A guest arrives without a reservation and hopes for a room for tonight.',
    department: 'front_office',
    difficulty: 1,
    isFree: false,
    personaPreview: 'Mr. Novak · Slovak · neutral',
    durationMinutes: 5,
    courseLevels: ['basic', 'intermediate'],
    assignmentType: 'checkin',
  },
  {
    id: 'checkin-room-with-view-request',
    title: 'Simple Check-In with a Request',
    titleEs: 'Check-in con petición especial',
    description: 'A guest with an existing reservation checks in and politely asks for a room with a view.',
    department: 'front_office',
    difficulty: 1,
    isFree: false,
    personaPreview: 'Mrs. Larsen · Danish · friendly',
    durationMinutes: 5,
    courseLevels: ['basic', 'intermediate'],
    assignmentType: 'checkin',
  },
  {
    id: 'checkin-missing-reservation-alternative',
    title: 'Missing Reservation',
    titleEs: 'Reserva no encontrada',
    description: "The system shows no record of the guest's reservation; an alternative must be found.",
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Haddad · Lebanese · confused',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'checkin',
  },
  {
    id: 'checkin-group-arrival',
    title: 'Group Check-In',
    titleEs: 'Llegada de un grupo',
    description: 'A tour group of ten arrives at once and needs an organized, efficient check-in.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Alves · Brazilian · neutral',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'checkin',
  },
  {
    id: 'checkin-card-declined',
    title: 'Card Declined at Check-In',
    titleEs: 'Tarjeta rechazada',
    description: "The guest's credit card is declined during the check-in deposit hold.",
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mrs. Ferreira · Portuguese · frustrated',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'checkin',
  },

  // ── Restaurant ────────────────────────────────────────────────────────────
  {
    id: 'restaurant-simple-order',
    title: 'Simple Dinner Order',
    titleEs: 'Pedido sencillo de cena',
    description: 'A guest orders a straightforward three-course dinner.',
    department: 'fnb',
    difficulty: 1,
    isFree: false,
    personaPreview: 'Mr. Rossi · Italian · friendly',
    durationMinutes: 5,
    courseLevels: ['basic', 'intermediate'],
    assignmentType: 'restaurant',
  },
  {
    id: 'restaurant-dish-of-day-question',
    title: 'Dish of the Day Inquiry',
    titleEs: 'Pregunta sobre el plato del día',
    description: 'A guest asks detailed questions about the dish of the day before ordering.',
    department: 'fnb',
    difficulty: 1,
    isFree: false,
    personaPreview: 'Mrs. Eriksson · Swedish · neutral',
    durationMinutes: 5,
    courseLevels: ['basic', 'intermediate'],
    assignmentType: 'restaurant',
  },
  {
    id: 'restaurant-wrong-dish-served',
    title: 'Wrong Dish Served',
    titleEs: 'Plato equivocado',
    description: 'The kitchen sends out the wrong dish and the guest must be handled gracefully.',
    department: 'fnb',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Becker · German · frustrated',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'restaurant',
  },
  {
    id: 'restaurant-no-table-wait-alternative',
    title: 'No Table Available',
    titleEs: 'Sin mesa disponible',
    description: 'The restaurant is fully booked; the guest must be offered a wait time or alternative.',
    department: 'fnb',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Ms. Tanaka · Japanese · neutral',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'restaurant',
  },
  {
    id: 'restaurant-wine-recommendation',
    title: 'Wine Recommendation Request',
    titleEs: 'Recomendación de vino',
    description: "A guest asks for a wine pairing recommendation for their meal.",
    department: 'fnb',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Fernández · Argentinian · friendly',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'restaurant',
  },

  // ── Hotel presentation ────────────────────────────────────────────────────
  {
    id: 'hotel-presentation-family-suite',
    title: 'Family Suite Presentation',
    titleEs: 'Presentación de suite familiar',
    description: 'A prospective guest tours the family suite and asks a question that must be politely declined.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mrs. Kowalski · Polish · friendly',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'hotel_presentation',
  },
  {
    id: 'hotel-presentation-business-traveller',
    title: 'Business Traveller Presentation',
    titleEs: 'Presentación para viajero de negocios',
    description: 'A business guest tours the work facilities and asks a question that must be politely declined.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Meyer · Swiss · neutral',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'hotel_presentation',
  },
  {
    id: 'hotel-presentation-honeymoon-package',
    title: 'Honeymoon Package Presentation',
    titleEs: 'Presentación del paquete de luna de miel',
    description: 'A guest planning her honeymoon asks for a discount that cannot be granted.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Ms. Muñoz · Chilean · friendly',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'hotel_presentation',
  },
  {
    id: 'hotel-presentation-spa-wellness',
    title: 'Spa & Wellness Presentation',
    titleEs: 'Presentación del spa y bienestar',
    description: 'A wellness-focused guest asks for private after-hours spa access, which must be politely declined.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. van Dijk · Dutch · demanding',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'hotel_presentation',
  },

  // ── Job interview ─────────────────────────────────────────────────────────
  {
    id: 'job-interview-front-office-trainee',
    title: 'Front Office Trainee Interview',
    titleEs: 'Entrevista para prácticas en recepción',
    description: 'A job interview for a front office trainee position with the hotel director.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Sra. Delgado · Spanish · neutral',
    durationMinutes: 8,
    courseLevels: ['intermediate'],
    assignmentType: 'job_interview',
  },
  {
    id: 'job-interview-fnb-waiter-trainee',
    title: 'F&B Waiter Trainee Interview',
    titleEs: 'Entrevista para prácticas de camarero',
    description: 'A job interview for a restaurant waiter trainee position with the hotel director.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Sr. Almeida · Portuguese · friendly',
    durationMinutes: 8,
    courseLevels: ['intermediate'],
    assignmentType: 'job_interview',
  },
  {
    id: 'job-interview-housekeeping-supervisor-trainee',
    title: 'Housekeeping Supervisor Trainee Interview',
    titleEs: 'Entrevista para prácticas de supervisor de pisos',
    description: 'A job interview for a housekeeping supervisor trainee position with the hotel director.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Sra. Marchetti · Italian · neutral',
    durationMinutes: 8,
    courseLevels: ['intermediate'],
    assignmentType: 'job_interview',
  },
  {
    id: 'job-interview-kitchen-assistant-trainee',
    title: 'Kitchen Assistant Trainee Interview',
    titleEs: 'Entrevista para prácticas de ayudante de cocina',
    description: 'A job interview for a kitchen assistant trainee position with the hotel director.',
    department: 'management',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Sr. Haas · German · demanding',
    durationMinutes: 8,
    courseLevels: ['intermediate'],
    assignmentType: 'job_interview',
  },

  // ── Saying no ─────────────────────────────────────────────────────────────
  {
    id: 'saying-no-early-checkin-unavailable',
    title: 'Early Check-In Not Available',
    titleEs: 'Check-in anticipado no disponible',
    description: 'A guest requests check-in hours before the room is ready and must be told no, with an alternative offered.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mrs. Johansson · Norwegian · neutral',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'saying_no',
  },
  {
    id: 'saying-no-pet-not-allowed',
    title: 'Pets Not Allowed',
    titleEs: 'No se admiten mascotas',
    description: 'A guest arrives with a small dog at a no-pets hotel and must be told no, with alternatives suggested.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Petrov · Russian · frustrated',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'saying_no',
  },
  {
    id: 'saying-no-discount-request',
    title: 'Unofficial Discount Request',
    titleEs: 'Petición de descuento no autorizado',
    description: 'A guest asks for a discount the receptionist has no authority to grant and must decline appropriately.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Osei · Ghanaian · demanding',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'saying_no',
  },
  {
    id: 'saying-no-room-upgrade-unavailable',
    title: 'Room Upgrade Not Available',
    titleEs: 'Mejora de habitación no disponible',
    description: 'A guest requests a free upgrade on a sold-out night and must be told no, with a fair alternative offered.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mrs. Petit · Belgian · friendly',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'saying_no',
  },
  {
    id: 'saying-no-late-checkout-unavailable',
    title: 'Late Checkout Not Possible',
    titleEs: 'Late check-out no disponible',
    description: 'A guest requests a very late checkout on a day the room is needed for an arriving guest.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Abara · Nigerian · neutral',
    durationMinutes: 6,
    courseLevels: ['intermediate'],
    assignmentType: 'saying_no',
  },

  // ── Complaint handling ────────────────────────────────────────────────────
  {
    id: 'complaint-slow-service',
    title: 'Slow Restaurant Service Complaint',
    titleEs: 'Queja por servicio lento',
    description: 'A guest complains about excessively slow service during breakfast.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Weber · Austrian · frustrated',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'complaint',
  },
  {
    id: 'complaint-wrong-bill',
    title: 'Incorrect Bill Complaint',
    titleEs: 'Queja por factura incorrecta',
    description: 'A guest finds unexpected charges on their final bill and demands an explanation.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mrs. Lindqvist · Finnish · demanding',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'complaint',
  },
  {
    id: 'complaint-room-not-cleaned',
    title: 'Room Not Cleaned Complaint',
    titleEs: 'Queja por habitación sin limpiar',
    description: 'A guest returns to find their room was never serviced that day.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Ms. Zhang · Chinese · frustrated',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'complaint',
  },
  {
    id: 'complaint-broken-ac',
    title: 'Broken Air Conditioning Complaint',
    titleEs: 'Queja por aire acondicionado averiado',
    description: 'A guest complains that the air conditioning has not worked all night.',
    department: 'front_office',
    difficulty: 2,
    isFree: false,
    personaPreview: 'Mr. Farouk · Egyptian · frustrated',
    durationMinutes: 7,
    courseLevels: ['intermediate'],
    assignmentType: 'complaint',
  },
  {
    id: 'complaint-double-charge-checkout',
    title: 'Double-Charged Card Complaint',
    titleEs: 'Queja por cobro duplicado',
    description: 'A guest discovers their card was charged twice after checkout.',
    department: 'front_office',
    difficulty: 3,
    isFree: false,
    personaPreview: 'Mrs. Petrova · Bulgarian · demanding',
    durationMinutes: 8,
    courseLevels: ['intermediate'],
    assignmentType: 'complaint',
  },
];

/** Scenarios visible to a given course level. */
export function scenariosForLevel(level: CourseLevel): ScenarioMeta[] {
  return SCENARIO_CATALOG.filter(s => s.courseLevels.includes(level));
}

// ── Loader ────────────────────────────────────────────────────────────────────

const SCENARIO_MODULES: Record<string, () => Scenario> = {
  'noisy-room-complaint':    () => require('@/content/scenarios/noisy-room-complaint.json') as Scenario,
  'restaurant-allergy-order': () => require('@/content/scenarios/restaurant-allergy-order.json') as Scenario,
  'overbooking':             () => require('@/content/scenarios/overbooking.json') as Scenario,
  'lost-luggage':            () => require('@/content/scenarios/lost-luggage.json') as Scenario,

  'checkin-walk-in-no-reservation':          () => require('@/content/scenarios/checkin-walk-in-no-reservation.json') as Scenario,
  'checkin-room-with-view-request':          () => require('@/content/scenarios/checkin-room-with-view-request.json') as Scenario,
  'checkin-missing-reservation-alternative': () => require('@/content/scenarios/checkin-missing-reservation-alternative.json') as Scenario,
  'checkin-group-arrival':                   () => require('@/content/scenarios/checkin-group-arrival.json') as Scenario,
  'checkin-card-declined':                   () => require('@/content/scenarios/checkin-card-declined.json') as Scenario,

  'restaurant-simple-order':            () => require('@/content/scenarios/restaurant-simple-order.json') as Scenario,
  'restaurant-dish-of-day-question':    () => require('@/content/scenarios/restaurant-dish-of-day-question.json') as Scenario,
  'restaurant-wrong-dish-served':       () => require('@/content/scenarios/restaurant-wrong-dish-served.json') as Scenario,
  'restaurant-no-table-wait-alternative': () => require('@/content/scenarios/restaurant-no-table-wait-alternative.json') as Scenario,
  'restaurant-wine-recommendation':     () => require('@/content/scenarios/restaurant-wine-recommendation.json') as Scenario,

  'hotel-presentation-family-suite':       () => require('@/content/scenarios/hotel-presentation-family-suite.json') as Scenario,
  'hotel-presentation-business-traveller': () => require('@/content/scenarios/hotel-presentation-business-traveller.json') as Scenario,
  'hotel-presentation-honeymoon-package':  () => require('@/content/scenarios/hotel-presentation-honeymoon-package.json') as Scenario,
  'hotel-presentation-spa-wellness':       () => require('@/content/scenarios/hotel-presentation-spa-wellness.json') as Scenario,

  'job-interview-front-office-trainee':            () => require('@/content/scenarios/job-interview-front-office-trainee.json') as Scenario,
  'job-interview-fnb-waiter-trainee':              () => require('@/content/scenarios/job-interview-fnb-waiter-trainee.json') as Scenario,
  'job-interview-housekeeping-supervisor-trainee': () => require('@/content/scenarios/job-interview-housekeeping-supervisor-trainee.json') as Scenario,
  'job-interview-kitchen-assistant-trainee':       () => require('@/content/scenarios/job-interview-kitchen-assistant-trainee.json') as Scenario,

  'saying-no-early-checkin-unavailable':  () => require('@/content/scenarios/saying-no-early-checkin-unavailable.json') as Scenario,
  'saying-no-pet-not-allowed':            () => require('@/content/scenarios/saying-no-pet-not-allowed.json') as Scenario,
  'saying-no-discount-request':           () => require('@/content/scenarios/saying-no-discount-request.json') as Scenario,
  'saying-no-room-upgrade-unavailable':   () => require('@/content/scenarios/saying-no-room-upgrade-unavailable.json') as Scenario,
  'saying-no-late-checkout-unavailable':  () => require('@/content/scenarios/saying-no-late-checkout-unavailable.json') as Scenario,

  'complaint-slow-service':          () => require('@/content/scenarios/complaint-slow-service.json') as Scenario,
  'complaint-wrong-bill':            () => require('@/content/scenarios/complaint-wrong-bill.json') as Scenario,
  'complaint-room-not-cleaned':      () => require('@/content/scenarios/complaint-room-not-cleaned.json') as Scenario,
  'complaint-broken-ac':             () => require('@/content/scenarios/complaint-broken-ac.json') as Scenario,
  'complaint-double-charge-checkout': () => require('@/content/scenarios/complaint-double-charge-checkout.json') as Scenario,
};

export function loadScenario(id: string): Scenario | null {
  return SCENARIO_MODULES[id]?.() ?? null;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

export const DEPT_LABELS: Partial<Record<Department, string>> = {
  front_office: 'Front Office',
  fnb:          'Food & Beverage',
  concierge:    'Concierge',
  housekeeping: 'Housekeeping',
  events:       'Events',
  management:   'Management',
};

export const MOOD_ICONS: Record<string, string> = {
  friendly:   '😊',
  neutral:    '😐',
  frustrated: '😤',
  demanding:  '🧐',
  confused:   '😟',
};
